$(document).ready(function(){
  $("#letras_on").hide();
  $("#LETRAS_on").hide();
  $("#number_on").hide();
  $("#caracter_on").hide();
  $(".letras_on").hide();
  $(".LETRAS_on").hide();
  $(".number_on").hide();
  $(".caracter_on").hide();

    $(".showhide_more").click(function(){
        $("#letras_on").toggle();
        $("#LETRAS_on").toggle();
        $("#number_on").toggle();
        $("#caracter_on").toggle();
        $(".letras_on").toggle();
        $(".LETRAS_on").toggle();
        $(".number_on").toggle();
        $(".caracter_on").toggle();
    });
});
